// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfQB3s-oAffIO0QVzCf6lJeLgsnQfF1eg',
    appId: '1:214817935459:web:56a600c05bd3349a5e2856',
    messagingSenderId: '214817935459',
    projectId: 'technicalsupport-70b7d',
    authDomain: 'technicalsupport-70b7d.firebaseapp.com',
    storageBucket: 'technicalsupport-70b7d.appspot.com',
    measurementId: 'G-KM0R5T23PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3KLTeyBVLW3N_GHinpt44OaMFdQ2Igc',
    appId: '1:214817935459:android:05483893316174095e2856',
    messagingSenderId: '214817935459',
    projectId: 'technicalsupport-70b7d',
    storageBucket: 'technicalsupport-70b7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBeyCFddYog9a264a1IPZijFgE2Qairdg',
    appId: '1:214817935459:ios:93e48d78e122160f5e2856',
    messagingSenderId: '214817935459',
    projectId: 'technicalsupport-70b7d',
    storageBucket: 'technicalsupport-70b7d.appspot.com',
    iosClientId: '214817935459-4m69jqkbkjoh2j0v91fan839sp4d9394.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBeyCFddYog9a264a1IPZijFgE2Qairdg',
    appId: '1:214817935459:ios:2deb5a8c8c28db215e2856',
    messagingSenderId: '214817935459',
    projectId: 'technicalsupport-70b7d',
    storageBucket: 'technicalsupport-70b7d.appspot.com',
    iosClientId: '214817935459-3rks1asai0aaao8o1jrovm6sm6jfvj1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniTraining.RunnerTests',
  );
}
